package:
  name: ncurses
  version: 5.9

source:
  fn: ncurses-5.9.tar.gz
  url: http://ftp.gnu.org/pub/gnu/ncurses/ncurses-5.9.tar.gz


about:
  home: http://www.gnu.org/software/ncurses/
  license: GPL
