package:
  name: pygtk
  version: 2.24.0

source:
  fn: pygtk-2.24.0.tar.gz
  url: https://pypi.python.org/packages/source/P/PyGTK/pygtk-2.24.0.tar.bz2
  md5: a1051d5794fd7696d3c1af6422d17a49

requirements:
  build:
    - python
    - glib
    - pygobject

  run:
    - python
    - glib
    - pygobject

test:
  imports:
    - pygtk

about:
  home: http://www.pygtk.org
  license: LGPL License
