package:
  name: pylint-django
  version: 0.5.5

source:
  fn: pylint-django-0.5.5.tar.gz
  url: https://pypi.python.org/packages/source/p/pylint-django/pylint-django-0.5.5.tar.gz
  md5: 774cbc7119615bf06d2f3eb88060cb66

requirements:
  build:
    - python
    - setuptools
    - pylint

  run:
    - python

about:
  home: https://github.com/landscapeio/pylint-django
  license: GPLv2
