package:
  name: qt
  version: 4.8.4

source:
  fn: qt-everywhere-opensource-src-4.8.4.tar.gz
  url: http://releases.qt-project.org/qt4/source/qt-everywhere-opensource-src-4.8.4.tar.gz
  md5: 89c5ecba180cae74c66260ac732dc5cb
  patches:
    - acceptance.patch

requirements:
  build:
    - freetype
    - fontconfig
    - dbus
    - libjpeg
    - libmysqlclient
  run:
    - dbus
    - freetype
    - fontconfig
    - libjpeg
    - libmysqlclient

build:
  number: 12

about:
    home: http://qt-project.org
    license: LGPL
