package:
  name: atlas
  version: 3.10.1

source:
  fn: atlas3.10.1.tar.bz2
  url: http://netcologne.dl.sourceforge.net/project/math-atlas/Stable/3.10.1/atlas3.10.1.tar.bz2


requirements:
  build:
    - blas
    - lapack


about:
  home: http://www.netlib.org/lapack/
  license: public domain
