package:
  name: pyside-tools
  version: 0.2.14

source:
  fn: pyside-tools-0.2.14.tar.bz2
  url: http://qt-project.org/uploads/pyside/pyside-tools-0.2.14.tar.bz2

build:
  number: 1    
 
requirements:
  build:
    - cmake     
    - qt        
    - libpng    
    - shiboken  
    - python
    - pyside
  run:
    - qt        
    - shiboken  
    - libpng
    - pyside
    - python


about:
  home: https://pypi.python.org/pypi/PySide
  license: LGPL
