package:
  name: conda
  version: 2.3.1

source:
  git_url: https://github.com/conda/conda.git
  #git_url: https://github.com/hajs/conda.git
  #patches:
  #  - repositories.patch

requirements:
  build:
    - python
    - distribute
    - pycosat
    - conda-build

  run:
    - python
    - pycosat
    - yaml
    - pyyaml
    - conda-build

build:
  number: 0

about:
  home: https://github.com/ContinuumIO/conda
  license: BSD
