package:
  name: conda
  version: 2.1.0

source:
  git_url: https://github.com/ContinuumIO/conda.git
  #git_url: https://github.com/hajs/conda.git
  patches:
    - repositories.patch

requirements:
  build:
    - python
    - distribute
    - pycosat

  run:
    - python
    - pycosat
    - yaml
    - pyyaml

build:
  number: 0

about:
  home: https://github.com/ContinuumIO/conda
  license: BSD
