package:
  name: conda
  version: 1.8.0

source:
  git_url: https://github.com/ContinuumIO/conda.git
  patches:
    - repositories.patch
    - bipath.patch

requirements:
  build:
    - python
    - distribute
    - pycosat

  run:
    - python
    - pycosat
    - yaml
    - pyyaml

about:
  home: https://github.com/ContinuumIO/conda
  license: free
