package:
  name: distribute
  version: 0.7.3

source:
  url: https://pypi.python.org/packages/source/d/distribute/distribute-0.7.3.zip
  fn: distribute-0.7.3.zip
  patches:
    - notzipsafe.patch


requirements:
  build:
    - python

  run:
    - python
    - setuptools


about:
  home: https://pypi.python.org/pypi/distribute
  license: PSF
