package:
  name: numba
  version: 0.11.0

source:
  git_url: https://github.com/numba/numba.git


requirements:
  build:
    - python
    - llvmpy
    - llvmmath
    - numpy
    - cython
    - distribute
    - cffi
    
  run:
    - python
    - llvmpy
    - llvmmath
    - numpy
    - cython
    - meta
    - cffi


build:
  number: 1


about:
  home: http://numba.pydata.org
  license: PSF
