about: {home: 'http://cairographics.org/', license: MIT}
build:
  entry_points: []
  features: []
  number: 0
  string: ''
  track_features: []
package: {name: pixman, version: 0.32.4}
requirements:
  build: []
  conflicts: []
  run: []
source:
  fn: pixman-0.32.4.tar.gz
  git_branch: ''
  git_tag: ''
  md5: eba449138b972fbf4547a8c152fea162
  patches: []
  svn_rev: ''
  url: http://cairographics.org/releases/pixman-0.32.4.tar.gz
test:
  commands: []
  files: []
  imports: []
  requires: []
