package:
  name: chardet
  version: 2.1.1

source:
  fn: chardet-2.1.1.tar.gz
  url: https://pypi.python.org/packages/source/c/chardet/chardet-2.1.1.tar.gz
  md5: 295367fd210d20f3febda615a88e1ef0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - chardet:main
    #
    # Would call chardet.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    # - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - chardet

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://github.com/erikrose/chardet
  license: GNU Library or Lesser General Public License (LGPL)

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
