package:
  name: alembic
  version: 0.6.0

source:
  fn: alembic-0.6.0.tar.gz
  url: https://pypi.python.org/packages/source/a/alembic/alembic-0.6.0.tar.gz
  md5: 084fe81b48ebae43b0f6031af68a03d6
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - alembic:main
    #
    # Would call alembic.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - sqlalchemy
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    # - distribute

  run:
    - python
    - sqlalchemy

test:
  # Python imports
  imports:
    - alembic

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/zzzeek/alembic
  license: MIT

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
