package:
  name: pympler
  version: 0.3.1

source:
  fn: Pympler-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/P/Pympler/Pympler-0.3.1.tar.gz
  md5: 906ce437f46fb30991007671a59d4319

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    - distribute
    - setuptools

  run:
    - python
    - distribute
    - setuptools

test:
  # Python imports
  imports:
    - pympler

about:
  home: http://pythonhosted.org/Pympler/
  license: Apache License, Version 2.0

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
