package:
  name: oursql
  version: 0.9.3.1

source:
  fn: oursql-0.9.3.1.tar.bz2
  url: https://pypi.python.org/packages/source/o/oursql/oursql-0.9.3.1.tar.bz2
  md5: 5ffab98306dbc5328ed1c436b85bfbe9
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - oursql:main
    #
    # Would call oursql.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - libmysqlclient
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    - distribute

  run:
    - python
    - libmysqlclient

test:
  # Python imports
  imports:
    - oursql

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://launchpad.net/oursql
  license: BSD License

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
