package:
  name: xlrd
  version: 0.9.2

source:
  fn: xlrd-0.9.2.tar.gz
  url: https://pypi.python.org/packages/source/x/xlrd/xlrd-0.9.2.tar.gz
  md5: 91a81ee76233e9f3115acaaa1b251b0e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - xlrd:main
    #
    # Would call xlrd.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    # - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - xlrd

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://www.python-excel.org/
  license: BSD License

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
