package:
  name: ninjaide
  version: 2.3

source:
  fn: ninaide-v2.3.zip
  url: https://github.com/ninja-ide/ninja-ide/archive/v2.3.zip
  #md5: 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - spyder = spyder:main
    #
    # Would create an entry point called spyder that calls spyder.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyqt
    - pyinotify

  run:
    - python
    - pyqt
    - ipython
    - rope
    - pylint
    - pep8
    - pyinotify

test:
  # Python imports
  #imports:
  #  - spyder

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://spyderlib.googlecode.com
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
