package:
  name: pyproj
  version: 1.9.3

source:
  url: http://pyproj.googlecode.com/files/pyproj-1.9.3.tar.gz
  fn: pyproj-1.9.3.tar.gz

requirements:
  build:
    - python
    - numpy

  run:
    - numpy

about:
  home: https://pyproj.googlecode.com
  license: MIT
