package:
  name: mc
  version: 4.8.10

source:
  #git_url: https://github.com/MidnightCommander/mc.git
  url: https://github.com/MidnightCommander/mc/archive/4.8.10.tar.gz
  fn: mc-4.8.10.tar.gz

requirements:
  build:
    - ncurses
    - slang
    - glib
    #- gettext
  run:
    - ncurses
    - slang
    - glib
    - gettext

about:
  home: http://www.midnight-commander.org/
  license: BSD
