package:
  name: twisted
  version: !!str 13.0.0

source:
  fn: Twisted-13.0.0.tar.bz2
  url: https://pypi.python.org/packages/source/T/Twisted/Twisted-13.0.0.tar.bz2
#  md5: 9625c094e0a18da77faa4627b98c9815
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - twisted = twisted:main
    #
    # Would create an entry point called twisted that calls twisted.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - zope.interface >=3.6.0

  run:
    - python
    - zope.interface >=3.6.0

test:
  # Python imports
  imports:
    - twisted

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://twistedmatrix.com/
  license: MIT
  summary: 'Twisted is an event-driven networking engine for Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
