package:
  name: numpy
  version: 1.7.1

source:
  url: https://pypi.python.org/packages/source/n/numpy/numpy-1.7.1.tar.gz
  fn: numpy-1.7.1.tar.gz

requirements:
  build:
    - python
    #- blas
    #- lapack
    - atlas

  run:
    - python
    - atlas

about:
  home: https://www.numpy.org
  license: PSF
