package:
  name: gribapi
  version: 1.11.0

source:
  fn: grib_api-1.9.9.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.9.9.tar.gz?api=v2
  #fn: grib_api-1.11.0.tar.gz
  #url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.11.0.tar.gz?api=v2

requirements:
  build:
    - python
    - numpy    
    - libpng
    - libjpeg
    - libjasper
    - libopenjpeg
    # - swig
  run:
    - python
    - numpy    
    - libpng
    - libjpeg
    - libjasper
    - libopenjpeg

build:
  number: 2


about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache
