package:
  name: numexpr
  version: 2.4.0

source:
  fn: numexpr-2.4.tar.gz
  url: https://pypi.python.org/packages/source/n/numexpr/numexpr-2.4.tar.gz

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - numexpr:main
    #
    # Would call numexpr.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    - distribute

  run:
    - python
    - numpy
    # - matplotlib
    # - statsmodels
    # - pytables
    # - openpyxl

test:
  # Python imports
  imports:
    - numexpr

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    #- python numexpr/tests/test_numexpr.py -v

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://code.google.com/p/numexpr/
  license: MIT

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
