package:
  name: pipe
  version: 1.3.1

source:
  url: https://pypi.python.org/packages/source/p/pip/pip-1.3.1.tar.gz
  fn: pip-1.3.1.tar.gz

requirements:
  build:
    - python

  run:
    - python


about:
  home: https://pypi.python.org/pypi/setuptools
  license: PSF
