package:
  name: nose
  #version: 1.0.0
  version: 1.3.0

source:
  #fn: nose-1.0.0.tar.gz
  #url: https://pypi.python.org/packages/source/n/nose/nose-1.0.0.tar.gz
  git_url: https://github.com/nose-devs/nose.git
  md5: 47a4784c817afa6ef11a505b574584ed
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nose:main
    #
    # Would call nose.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    # - distribute

  run:
    - python
    - coverage

test:
  # Python imports
  imports:
    - nose

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://somethingaboutorange.com/mrl/projects/nose/
  license: GNU Library or Lesser General Public License (LGPL)

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
