package:
  name: conda
  version: 1.8.0

source:
  git_url: https://github.com/ContinuumIO/conda.git


requirements:
  build:
    - python
    - distribute
    - pycosat

  run:
    - python
    - pycosat
    - pyaml
    - pyaml

about:
  home: https://github.com/ContinuumIO/conda
  license: 
