package:
  name: beaver
  version: !!str 31

source:
  fn: Beaver-31.tar.gz
  url: https://pypi.python.org/packages/source/B/Beaver/Beaver-31.tar.gz
  md5: 733e775cb5f25335f013096a70e06c16
  patches:
   # List any patch files here
   - requirements.patch

build:
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - beaver = beaver:main
    #
    # Would create an entry point called beaver that calls beaver.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - distribute
    # for amazon sqs: - boto >=2.8.0
    - conf_d >=0.0.4
    - glob2 #==0.3
    # for mqtt: - mosquitto >=1.1
    - msgpack-pure >=0.1.3
    - pika >=0.9.12
    - python-daemon >=1.5.2
    - redis >=2.7.5

  run:
    - python
    # for amazon sqs: - boto >=2.8.0
    - conf_d >=0.0.4
    - glob2 #==0.3
    # for mqtt: - mosquitto >=1.1
    - msgpack-pure >=0.1.3
    - pika >=0.9.12
    - python-daemon >=1.5.2
    - redis >=2.7.5

test:
  # Python imports
  imports:
    - beaver
    - beaver.dispatcher
    - beaver.tests
    - beaver.transports
    - beaver.worker

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/josegonzalez/beaver
  license: MIT License
  summary: 'python daemon that munches on logs and sends their contents to logstash'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
