package:
  name: rope
  version: 0.9.4

source:
  fn: rope-0.9.4.tar.gz
  url: https://pypi.python.org/packages/source/r/rope/rope-0.9.4.tar.gz
  md5: 6c654c6892f78008e04e2d65f9f859bb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rope = rope:main
    #
    # Would create an entry point called rope that calls rope.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - rope

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://rope.sf.net/
  license: GNU General Public License (GPL)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
