package:
  name: matplotlib
  version: 1.2.1

source:
  url: https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.2.1/matplotlib-1.2.1.tar.gz
  fn: matplotlib-1.2.1.tar.gz

requirements:
  build:
    - python
    - numpy
    - freetype
    - bzip2

  run:
    - python
    - numpy
    - freetype
    - bzip2

build:
  number: 1

about:
  home: http://www.matplotlib.org
  license: BSD
