package:
  name: graphite-web
  version: !!str 0.9.12

source:
  fn: graphite-web-0.9.12.tar.gz
  url: https://pypi.python.org/packages/source/g/graphite-web/graphite-web-0.9.12.tar.gz
  md5: 8edbb61f1ffe11c181bd2cb9ec977c72
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - graphite-web = graphite-web:main
    #
    # Would create an entry point called graphite-web that calls graphite-web.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python

  run:
    - python
    - django-tagging
    - pytz
    

test:
  # Python imports
  imports:
    - graphite
    - graphite.account
    - graphite.browser
    - graphite.cli
    - graphite.composer
    - graphite.dashboard
    - graphite.events
    - graphite.graphlot
    - graphite.metrics
    - graphite.render
    - graphite.thirdparty
    - graphite.thirdparty.pytz
    - graphite.version
    - graphite.whitelist

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://graphite-project.github.com
  license: Apache Software License 2.0
  summary: 'Enterprise scalable realtime graphing'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
