package:
  name: hdf5
  version: 1.8.12

source:
  fn: hdf5-1.8.12.tar.bz2
  url: http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.12.tar.bz2

build:
  number: 0

about:
  home: http://hdfgroup.org
  license: BSD
