package:
  name: scikit-image
  version: 0.10.1

source:
  fn: scikit-image-0.10.1.tar.gz
  url: https://pypi.python.org/packages/source/s/scikit-image/scikit-image-0.10.1.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scikit-image = scikit-image:main
    #
    # Would create an entry point called scikit-image that calls scikit-image.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - scipy
    - setuptools
    - cython
    - six

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - six   
    - cython    

test:
  # Python imports
  # imports:

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://scikit-image.org
  license: BSD License
  summary: 'Image processing routines for SciPy'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
