package:
  name: python
  version: 2.7.9


source:
  fn: Python-2.7.9.tar.gz
  url: https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz


requirements:
  build:
     - openssl
     - readline
     - sqlite
     - system
     - zlib
     - bzip2
  run:
     - openssl
     - readline
     - sqlite
     - system
     - zlib
     - bzip2


build:
  number: 0


about:
  home: http://www.python.org
  license: PSF
