package:
  name: pip
  version: 1.4.1

source:
  url: https://pypi.python.org/packages/source/p/pip/pip-1.4.1.tar.gz
  md5: 6afbb46aeb48abac658d4df742bff714
  fn: pip-1.4.1.tar.gz

requirements:
  build:
    - python
    - distribute
    - setuptools

  run:
    - python
    - distribute
    - setuptools
    
build:
  number: 0
  entry_points:
    - pip = pip.runner:run


about:
  home: https://www.pip-installer.org
  license: PSF
