package:
  name: pygrib
  #version: 1.9.6
  version: 1.9.9

source:
  fn: pygrib-1.9.2.tar.gz
  url: http://pygrib.googlecode.com/files/pygrib-1.9.2.tar.gz
  #fn: pygrib-1.9.3.tar.gz 
  #url: http://pygrib.googlecode.com/files/pygrib-1.9.3.tar.gz
  #url: http://pygrib.googlecode.com/files/pygrib-1.9.6.tar.gz
  #url: https://pypi.python.org/packages/source/p/pygrib/pygrib-1.9.9.tar.gz
  #md5: 10398d2dcac92a1cfe63042a84797507
  #svn_url: http://pygrib.googlecode.com/svn/trunk/
  patches:
   - voidp.patch

requirements:
  build:
    - python
    - numpy    
    - pyproj
    - gribapi
  run:
    - gribapi
    - python
    - numpy    
    - pyproj

build:
  number: 6

about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache
