package:
  name: basemap
  version: 1.2.1
  # XXX: wrong version, cannot be fixed but correct version would be lower

source:
  url: http://kent.dl.sourceforge.net/project/matplotlib/matplotlib-toolkits/basemap-1.0.7/basemap-1.0.7.tar.gz
  fn: basemap-1.0.7.tar.gz

requirements:
  build:
    - python
    - matplotlib
    - pyproj
    - numpy
    - pillow
    
  run:
    - numpy
    - pyproj
    - matplotlib
    - pillow

build:
  number: 1

about:
  home: http://www.matplotlib.org
  license: BSD
