package:
  name: dsltools
  version: 0.2.5

source:
  fn: dsltools-0.2.5.tar.gz
  url: https://pypi.python.org/packages/source/d/dsltools/dsltools-0.2.5.tar.gz
  md5: eacd33f795d6a34e1a8eda37e61abb37
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - dsltools = dsltools:main
    #
    # Would create an entry point called dsltools that calls dsltools.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - setuptools

  run:
    - python
    - nose



test:
  # Python imports
  imports:
    - dsltools

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - numpy
    - nose

about:
  home: http://github.com/iskandr/dsltools
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
