package:
  name: django
  version: 1.7.1

source:
  fn: Django-1.7.1.tar.gz
  url: https://pypi.python.org/packages/source/D/Django/Django-1.7.1.tar.gz
  md5: 81dae89f21647b9aa5c46c6b7dbfa349
#  patches:
   # List any patch files here
   # - fix.patch

build:
  entry_points:
    - django-admin = django.core.management:execute_from_command_line
    - django-admin.py = django.core.management:execute_from_command_line    
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django = django:main
    #
    # Would create an entry point called django that calls django.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - setuptools

  run:
    - python
    - pytz
    - setuptools
    - distribute

test:
  # Python imports
  imports:
    - django

  commands:
    - django-admin --help
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.djangoproject.com/
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
