package:
  name: vobject
  version: 0.8.1c

source:
  fn: vobject-0.8.1c.tar.gz
  url: https://pypi.python.org/packages/source/v/vobject/vobject-0.8.1c.tar.gz
  md5: c9686dd74d39fdae140890d9c694c076
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - vobject = vobject:main
    #
    # Would create an entry point called vobject that calls vobject.main()

    - ics_diff = vobject.ics_diff:main
    - change_tz = vobject.change_tz:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - setuptools
    - distribute
    - dateutil

  run:
    - python
    - dateutil

test:
  # Python imports
  imports:
    - vobject

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    #- ics_diff --help
    #- change_tz --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://vobject.skyhouseconsulting.com
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
