package:
  name: llvmpy
  version: 3.2

source:
  git_url: https://github.com/llvmpy/llvmpy


requirements:
  build:
    - python
    - llvm

  run:
    - python
    - llvm

build:
  number: 0


about:
  home: https://github.com/llvmpy
  license: PSF
