package:
  name: readline
  version: 6.2

build:
  number: 1

source:
  fn: readline-6.2.tar.gz
  url: ftp://ftp.cwru.edu/pub/bash/readline-6.2.tar.gz
  patches:
    - readline-link-ncurses.patch

requirements:
  build:
     - ncurses
  run:
     - ncurses


about:
  home: http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL
