package:
  name: lapack
  version: 3.4.2

source:
  fn: lapack.tgz
  url: http://www.netlib.org/lapack/lapack.tgz
  patches:
    - shared.patch


requirements:
  build:
    - blas    
  run:
    - blas

about:
  home: http://www.netlib.org/lapack/
  license: BSD
