package:
  name: conda-build
  version: 2.3.2

source:
  git_url: https://github.com/conda/conda-build.git

requirements:
  build:
    - python
    - distribute
    - pycosat
    - patchelf

  run:
    - python
    - pycosat
    - yaml
    - pyyaml
    - patchelf


build:
  number: 0

about:
  home: https://github.com/ContinuumIO/conda
  license: BSD
