package:
  name: meta
  version: 0.4.0

source:
  git_url: https://github.com/numba/Meta.git


requirements:
  build:
    - python
    - distribute
    - setuptools

  run:
    - python


build:
  number: 0


about:
  home: https://github.com/numba/Meta
  license: PSF
