package:
  name: libqwt
  version: 6.1.0

source:
  fn: qwt-6.1.0.tar.bz2
  url: http://downloads.sourceforge.net/project/qwt/qwt/6.1.0/qwt-6.1.0.tar.bz2
  patches:
    - install.patch

build:
  number: 1

requirements:
  build:
   - qt
  run:
   - qt

about:
  home: http://sourceforge.net/projects/qwt/
  license: GPL
