package:
  name: statsmodels
  version: 0.6.1

source:
  fn: statsmodels-0.6.1.tar.gz
  url: http://pypi.python.org/packages/source/s/statsmodels/statsmodels-0.6.1.tar.gz
  md5: f7580ebf7d2a2c9b87abfad190dcb9a3

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - statsmodels:main
    #
    # Would call statsmodels.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - scipy
    - setuptools
    - distribute
    - pandas
    - dateutil
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    # - distribute

  run:
    - numpy
    - scipy
    - pandas
    - dateutil
    - python

test:
  # Python imports
  imports:
    - statsmodels

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://statsmodels.sourceforge.net/
  license: BSD License

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
