package:
  name: suds
  version: 0.4

source:
  fn: suds-0.4.tar.gz
  url: https://pypi.python.org/packages/source/s/suds/suds-0.4.tar.gz
  md5: b7502de662341ed7275b673e6bd73191
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - suds:main
    #
    # Would call suds.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - lxml
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    - setuptools
    - distribute

  run:
    - python
    - lxml

test:
  # Python imports
  imports:
    - suds

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://fedorahosted.org/suds
  license: LGPL

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
