package:
  name: carbon
  version: !!str 0.9.12

source:
  fn: carbon-0.9.12.tar.gz
  url: https://pypi.python.org/packages/source/c/carbon/carbon-0.9.12.tar.gz
  md5: 66967d5a622fd29973838fcd10eb34f3
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - carbon = carbon:main
    #
    # Would create an entry point called carbon that calls carbon.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - twisted
    - txamqp

  run:
    - python
    - twisted
    - txamqp

test:
  # Python imports
  imports:
    - carbon
    - carbon.aggregator
    - twisted.plugins

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://graphite-project.github.com
  license: Apache Software License 2.0
  summary: 'Backend data caching and persistence daemon for Graphite'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
