package:
  name: flup
  version: 1.0.2

source:
  fn: flup-1.0.2.tar.gz
  url: https://pypi.python.org/packages/source/f/flup/flup-1.0.2.tar.gz
  md5: 24dad7edc5ada31dddd49456ee8d5254
  patches:
   # List any patch files here
    - zip.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flup = flup:main
    #
    # Would create an entry point called flup that calls flup.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - flup

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.saddi.com/software/flup/
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
