package:
  name: shiboken
  version: 1.2.0

source:
  url: http://download.qt-project.org/official_releases/pyside/shiboken-1.2.0.tar.bz2
  fn: shiboken-1.2.0.tar.bz2

requirements:
  build:
    - cmake
    - qt
    - python
  run:
    - qt
    - python

build:
  number: 1

#test:
#  commands:
#    - shiboken --help
#  imports:
#    - shiboken

about:
    home: https://github.com/PySide/Shiboken
    license: LGPL
