package:
  name: pillow
  version: 1.7.8

source:
  fn: Pillow-1.7.8.zip
  url: https://pypi.python.org/packages/source/P/Pillow/Pillow-1.7.8.zip
  md5: 41d8688d4db72673069a6dc63b5289d6
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - Pillow:main
    #
    # Would call Pillow.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    # - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - Pillow

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://github.com/python-imaging/Pillow
  license: BSD

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
