package:
  name: wsgi_intercept
  version: 0.9.1

source:
  fn: wsgi_intercept-0.9.1.tar.gz
  url: https://pypi.python.org/packages/source/w/wsgi_intercept/wsgi_intercept-0.9.1.tar.gz
  #md5: c6d6abf4251a84e4381dd434f2a7f050
  #svn_url: http://wsgi-intercept.googlecode.com/svn/trunk/
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - wsgi_intercept = wsgi_intercept:main
    #
    # Would create an entry point called wsgi_intercept that calls wsgi_intercept.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python
    - distribute
    - setuptools

  run:
    - python


test:
  # Python imports
  imports:
    - wsgi_intercept

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/wsgi_intercept
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
