package:
  name: sphinx
  version: 1.2b1

source:
  fn: Sphinx-1.2b1.tar.gz
  url: https://pypi.python.org/packages/source/S/Sphinx/Sphinx-1.2b1.tar.gz
  md5: 67bea6df63be8e2a76ebedc76d8f71a3
#  patches:
   # List any patch files here
   # - fix.patch

build:
  entry_points:
    - sphinx-build = sphinx:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main
    - sphinx-apidoc = sphinx.apidoc:main
    - sphinx-quickstart = sphinx.quickstart:main
    #
    # Would call Sphinx.main()


  number: 1

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    # - distribute
    - docutils
    - pygments
    - jinja2

  run:
    - python
    - docutils
    - pygments
    - jinja2


test:
  # Python imports
  #imports:
  #  - Sphinx

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://sphinx-doc.org/
  license: BSD License

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
