package:
  name: pyephem
  version: !!str 3.7.5.2

source:
  fn: pyephem-3.7.5.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pyephem/pyephem-3.7.5.2.tar.gz
  md5: b146a080d97618ca40e4e52b9b2ee814
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyephem = pyephem:main
    #
    # Would create an entry point called pyephem that calls pyephem.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - ephem
    - ephem.tests
#    - pyephem

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://rhodesmill.org/pyephem/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'Scientific-grade astronomy routines'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
