package:
  name: geoalchemy
  version: 0.7.2

source:
  fn: GeoAlchemy-0.7.2.tar.gz
  url: https://pypi.python.org/packages/source/G/GeoAlchemy/GeoAlchemy-0.7.2.tar.gz
  md5: e52d66af92aa2db035c97cc6f448cd07
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - GeoAlchemy:main
    #
    # Would call GeoAlchemy.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - sqlalchemy
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    - setuptools

  run:
    - python
    - sqlalchemy

test:
  # Python imports
  #imports:
  #  - GeoAlchemy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://geoalchemy.org/
  license: MIT License

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
