package:
  name: elasticsearch
  version: 1.3.1

source:
  fn : elasticsearch-1.3.1.zip
  url: https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.1.zip

requirements:
#  build:
#    - 
  run:
    - jre

build:
  number: 0

about:
  home: http://logstash.net
  license: BSD
