package:
  name: pytracemalloc
  version: 1.0.0

source:
  fn: pytracemalloc-1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pytracemalloc/pytracemalloc-1.0.tar.gz


# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - webtest = webtest:main
    #
    # Would create an entry point called webtest that calls webtest.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python_tracemalloc
    - distribute
    - setuptools

  run:
    - python_tracemalloc


test:
  # Python imports
  #imports:
  #  - tracemalloc

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pytracemalloc.readthedocs.org
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
