package:
  name: pyqtgraph
  version: 0.9.8

source:
  fn: pyqtgraph-0.9.8.tar.gz
  url: https://pypi.python.org/packages/source/p/pyqtgraph/pyqtgraph-0.9.8.tar.gz
  md5: 2b67bf1a0b9b9dded5654efa0c82ab38

requirements:
  build:
    - python
    - numpy
    - scipy

  run:
    - pyqt
    - python
    - numpy
    - scipy

test:
  imports:
    - pyqtgraph

about:
  home: http://www.pyqtgraph.org
  license: MIT License
